version: '3'

tasks:
  # Rust tasks
  rust.fmt:
    desc: Format Rust code
    dir: rust
    cmds:
      - cargo fmt

  rust.fmt-check:
    desc: Check Rust code formatting (without changing files)
    dir: rust
    cmds:
      - cargo fmt -- --check

  rust.lint:
    desc: Lint Rust code
    dir: rust
    cmds:
      - cargo clippy

  rust.lint-fix:
    desc: Automatically fix some Rust lint issues
    dir: rust
    cmds:
      - cargo clippy --fix

  rust.check:
    desc: Check Rust compilation without producing artifacts
    dir: rust
    cmds:
      - cargo check

  rust.test:
    desc: Run Rust tests
    dir: rust
    cmds:
      - cargo test

  # Dart/Flutter tasks
  flutter.fmt:
    desc: Format Dart code
    cmds:
      - dart format .

  flutter.fmt-check:
    desc: Check Dart code formatting (without changing files)
    cmds:
      - dart format --set-exit-if-changed .

  flutter.lint:
    desc: Run Flutter analyzer
    cmds:
      - flutter analyze

  flutter.lint-fix:
    desc: Fix Dart code issues where possible
    cmds:
      - dart fix --apply

  flutter.test:
    desc: Run Flutter tests
    cmds:
      - flutter test

  rust.fix:
    desc: Fix Rust code issues where possible
    dir: rust
    cmds:
      - cargo clippy --fix --allow-dirty

  flutter.fix:
    desc: Fix all Dart code issues where possible
    cmds:
      - dart fix --apply
      - dart format .

  flutter.get:
    desc: Get Flutter dependencies
    cmds:
      - flutter pub get

  # Combined tasks
  fix:
    desc: Fix both Rust and Flutter code issues
    deps:
      - task: rust.fix
      - task: flutter.fix

  fmt:
    desc: Format both Rust and Flutter code
    deps:
      - task: rust.fmt
      - task: flutter.fmt

  lint:
    desc: Lint both Rust and Flutter code
    deps:
      - task: rust.lint
      - task: flutter.lint

  check:
    desc: Check both Rust and Flutter code
    deps:
      - task: rust.check
      - task: flutter.lint

  test:
    desc: Run tests for both Rust and Flutter
    deps:
      - task: rust.test
      - task: flutter.test

  # Full development cycle
  all:
    desc: Run format, lint, and test for both Rust and Flutter
    deps:
      - task: fmt
      - task: lint
      - task: test