// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1423957431;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__api__add_session_layer_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "add_session_layer",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u32>::sse_decode(&mut deserializer);
            let api_layer_config =
                <crate::api::dart_types::LayerConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::api::add_session_layer(api_session_id, api_layer_config)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__api__create_new_map_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_new_map_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_engine_handle = <i64>::sse_decode(&mut deserializer);
            let api_config = <crate::api::dart_types::MapInitConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::api::create_new_map_session(api_engine_handle, api_config)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__api__destroy_all_engine_sessions_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "destroy_all_engine_sessions",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_engine_id = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::api::destroy_all_engine_sessions(api_engine_id);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__api__destroy_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "destroy_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::api::destroy_session(api_session_id);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__api__galileo_flutter_init_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "galileo_flutter_init",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_ffi_ptr = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::api::galileo_flutter_init(api_ffi_ptr);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__api__get_map_viewport_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_map_viewport",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::api::get_map_viewport(api_session_id))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__api__handle_event_for_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "handle_event_for_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u32>::sse_decode(&mut deserializer);
            let api_event = <crate::api::dart_types::UserEvent>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::api::handle_event_for_session(api_session_id, api_event);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__api__init_galileo_flutter_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_galileo_flutter",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::api::init_galileo_flutter();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__dart_types__map_init_config_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "map_init_config_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::dart_types::MapInitConfig::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__api__mark_session_alive_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "mark_session_alive",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::api::mark_session_alive(api_session_id);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__api__request_map_redraw_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "request_map_redraw",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::api::request_map_redraw(api_session_id)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__api__resize_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "resize_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <u32>::sse_decode(&mut deserializer);
            let api_new_size = <crate::api::dart_types::MapSize>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok =
                            crate::api::api::resize_session(api_session_id, api_new_size)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::api::CreateNewSessionResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <u32>::sse_decode(deserializer);
        let mut var_textureId = <i64>::sse_decode(deserializer);
        return crate::api::api::CreateNewSessionResponse {
            session_id: var_sessionId,
            texture_id: var_textureId,
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::dart_types::LayerConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::dart_types::LayerConfig::Osm;
            }
            1 => {
                let mut var_urlTemplate = <String>::sse_decode(deserializer);
                let mut var_attribution = <Option<String>>::sse_decode(deserializer);
                return crate::api::dart_types::LayerConfig::RasterTiles {
                    url_template: var_urlTemplate,
                    attribution: var_attribution,
                };
            }
            2 => {
                let mut var_urlTemplate = <String>::sse_decode(deserializer);
                let mut var_styleJson = <String>::sse_decode(deserializer);
                let mut var_attribution = <Option<String>>::sse_decode(deserializer);
                return crate::api::dart_types::LayerConfig::VectorTiles {
                    url_template: var_urlTemplate,
                    style_json: var_styleJson,
                    attribution: var_attribution,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::dart_types::MapInitConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_latlon = <(f64, f64)>::sse_decode(deserializer);
        let mut var_zoomLevel = <u32>::sse_decode(deserializer);
        let mut var_mapSize = <crate::api::dart_types::MapSize>::sse_decode(deserializer);
        let mut var_enableMultisampling = <bool>::sse_decode(deserializer);
        let mut var_backgroundColor = <(f32, f32, f32, f32)>::sse_decode(deserializer);
        return crate::api::dart_types::MapInitConfig {
            latlon: var_latlon,
            zoom_level: var_zoomLevel,
            map_size: var_mapSize,
            enable_multisampling: var_enableMultisampling,
            background_color: var_backgroundColor,
        };
    }
}

impl SseDecode for crate::api::dart_types::MapSize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        return crate::api::dart_types::MapSize {
            width: var_width,
            height: var_height,
        };
    }
}

impl SseDecode for crate::api::dart_types::MapViewport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_xMin = <f64>::sse_decode(deserializer);
        let mut var_xMax = <f64>::sse_decode(deserializer);
        let mut var_yMin = <f64>::sse_decode(deserializer);
        let mut var_yMax = <f64>::sse_decode(deserializer);
        return crate::api::dart_types::MapViewport {
            x_min: var_xMin,
            x_max: var_xMax,
            y_min: var_yMin,
            y_max: var_yMax,
        };
    }
}

impl SseDecode for crate::api::dart_types::MouseButton {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::dart_types::MouseButton::Left,
            1 => crate::api::dart_types::MouseButton::Middle,
            2 => crate::api::dart_types::MouseButton::Right,
            3 => crate::api::dart_types::MouseButton::Other,
            _ => unreachable!("Invalid variant for MouseButton: {}", inner),
        };
    }
}

impl SseDecode for crate::api::dart_types::MouseButtonState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::dart_types::MouseButtonState::Pressed,
            1 => crate::api::dart_types::MouseButtonState::Released,
            _ => unreachable!("Invalid variant for MouseButtonState: {}", inner),
        };
    }
}

impl SseDecode for crate::api::dart_types::MouseButtonsState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_left = <crate::api::dart_types::MouseButtonState>::sse_decode(deserializer);
        let mut var_middle = <crate::api::dart_types::MouseButtonState>::sse_decode(deserializer);
        let mut var_right = <crate::api::dart_types::MouseButtonState>::sse_decode(deserializer);
        return crate::api::dart_types::MouseButtonsState {
            left: var_left,
            middle: var_middle,
            right: var_right,
        };
    }
}

impl SseDecode for crate::api::dart_types::MouseEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_screenPointerPosition =
            <crate::api::dart_types::Point2>::sse_decode(deserializer);
        let mut var_buttons = <crate::api::dart_types::MouseButtonsState>::sse_decode(deserializer);
        return crate::api::dart_types::MouseEvent {
            screen_pointer_position: var_screenPointerPosition,
            buttons: var_buttons,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::dart_types::MapViewport> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::dart_types::MapViewport>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::dart_types::Point2 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_x = <f64>::sse_decode(deserializer);
        let mut var_y = <f64>::sse_decode(deserializer);
        return crate::api::dart_types::Point2 { x: var_x, y: var_y };
    }
}

impl SseDecode for (f32, f32, f32, f32) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <f32>::sse_decode(deserializer);
        let mut var_field1 = <f32>::sse_decode(deserializer);
        let mut var_field2 = <f32>::sse_decode(deserializer);
        let mut var_field3 = <f32>::sse_decode(deserializer);
        return (var_field0, var_field1, var_field2, var_field3);
    }
}

impl SseDecode for (f64, f64) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <f64>::sse_decode(deserializer);
        let mut var_field1 = <f64>::sse_decode(deserializer);
        return (var_field0, var_field1);
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::dart_types::UserEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 =
                    <crate::api::dart_types::MouseButton>::sse_decode(deserializer);
                let mut var_field1 = <crate::api::dart_types::MouseEvent>::sse_decode(deserializer);
                return crate::api::dart_types::UserEvent::ButtonPressed(var_field0, var_field1);
            }
            1 => {
                let mut var_field0 =
                    <crate::api::dart_types::MouseButton>::sse_decode(deserializer);
                let mut var_field1 = <crate::api::dart_types::MouseEvent>::sse_decode(deserializer);
                return crate::api::dart_types::UserEvent::ButtonReleased(var_field0, var_field1);
            }
            2 => {
                let mut var_field0 =
                    <crate::api::dart_types::MouseButton>::sse_decode(deserializer);
                let mut var_field1 = <crate::api::dart_types::MouseEvent>::sse_decode(deserializer);
                return crate::api::dart_types::UserEvent::Click(var_field0, var_field1);
            }
            3 => {
                let mut var_field0 =
                    <crate::api::dart_types::MouseButton>::sse_decode(deserializer);
                let mut var_field1 = <crate::api::dart_types::MouseEvent>::sse_decode(deserializer);
                return crate::api::dart_types::UserEvent::DoubleClick(var_field0, var_field1);
            }
            4 => {
                let mut var_field0 = <crate::api::dart_types::MouseEvent>::sse_decode(deserializer);
                return crate::api::dart_types::UserEvent::PointerMoved(var_field0);
            }
            5 => {
                let mut var_field0 =
                    <crate::api::dart_types::MouseButton>::sse_decode(deserializer);
                let mut var_field1 = <crate::api::dart_types::MouseEvent>::sse_decode(deserializer);
                return crate::api::dart_types::UserEvent::DragStarted(var_field0, var_field1);
            }
            6 => {
                let mut var_field0 =
                    <crate::api::dart_types::MouseButton>::sse_decode(deserializer);
                let mut var_field1 = <crate::api::dart_types::Vector2>::sse_decode(deserializer);
                let mut var_field2 = <crate::api::dart_types::MouseEvent>::sse_decode(deserializer);
                return crate::api::dart_types::UserEvent::Drag(var_field0, var_field1, var_field2);
            }
            7 => {
                let mut var_field0 =
                    <crate::api::dart_types::MouseButton>::sse_decode(deserializer);
                let mut var_field1 = <crate::api::dart_types::MouseEvent>::sse_decode(deserializer);
                return crate::api::dart_types::UserEvent::DragEnded(var_field0, var_field1);
            }
            8 => {
                let mut var_field0 = <f64>::sse_decode(deserializer);
                let mut var_field1 = <crate::api::dart_types::MouseEvent>::sse_decode(deserializer);
                return crate::api::dart_types::UserEvent::Scroll(var_field0, var_field1);
            }
            9 => {
                let mut var_field0 = <f64>::sse_decode(deserializer);
                let mut var_field1 = <crate::api::dart_types::Point2>::sse_decode(deserializer);
                return crate::api::dart_types::UserEvent::Zoom(var_field0, var_field1);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::dart_types::Vector2 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_dx = <f64>::sse_decode(deserializer);
        let mut var_dy = <f64>::sse_decode(deserializer);
        return crate::api::dart_types::Vector2 {
            dx: var_dx,
            dy: var_dy,
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__api__add_session_layer_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__api__create_new_map_session_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__api__destroy_all_engine_sessions_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        4 => wire__crate__api__api__destroy_session_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__api__galileo_flutter_init_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__api__get_map_viewport_impl(port, ptr, rust_vec_len, data_len),
        7 => {
            wire__crate__api__api__handle_event_for_session_impl(port, ptr, rust_vec_len, data_len)
        }
        8 => wire__crate__api__api__init_galileo_flutter_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__dart_types__map_init_config_default_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        10 => wire__crate__api__api__mark_session_alive_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__api__request_map_redraw_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__api__api__resize_session_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::api::CreateNewSessionResponse {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.texture_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::api::CreateNewSessionResponse
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::api::CreateNewSessionResponse>
    for crate::api::api::CreateNewSessionResponse
{
    fn into_into_dart(self) -> crate::api::api::CreateNewSessionResponse {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dart_types::LayerConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::dart_types::LayerConfig::Osm => [0.into_dart()].into_dart(),
            crate::api::dart_types::LayerConfig::RasterTiles {
                url_template,
                attribution,
            } => [
                1.into_dart(),
                url_template.into_into_dart().into_dart(),
                attribution.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::dart_types::LayerConfig::VectorTiles {
                url_template,
                style_json,
                attribution,
            } => [
                2.into_dart(),
                url_template.into_into_dart().into_dart(),
                style_json.into_into_dart().into_dart(),
                attribution.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dart_types::LayerConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dart_types::LayerConfig>
    for crate::api::dart_types::LayerConfig
{
    fn into_into_dart(self) -> crate::api::dart_types::LayerConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dart_types::MapInitConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.latlon.into_into_dart().into_dart(),
            self.zoom_level.into_into_dart().into_dart(),
            self.map_size.into_into_dart().into_dart(),
            self.enable_multisampling.into_into_dart().into_dart(),
            self.background_color.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dart_types::MapInitConfig
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dart_types::MapInitConfig>
    for crate::api::dart_types::MapInitConfig
{
    fn into_into_dart(self) -> crate::api::dart_types::MapInitConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dart_types::MapSize {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dart_types::MapSize
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dart_types::MapSize>
    for crate::api::dart_types::MapSize
{
    fn into_into_dart(self) -> crate::api::dart_types::MapSize {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dart_types::MapViewport {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.x_min.into_into_dart().into_dart(),
            self.x_max.into_into_dart().into_dart(),
            self.y_min.into_into_dart().into_dart(),
            self.y_max.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dart_types::MapViewport
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dart_types::MapViewport>
    for crate::api::dart_types::MapViewport
{
    fn into_into_dart(self) -> crate::api::dart_types::MapViewport {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dart_types::MouseButton {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Left => 0.into_dart(),
            Self::Middle => 1.into_dart(),
            Self::Right => 2.into_dart(),
            Self::Other => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dart_types::MouseButton
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dart_types::MouseButton>
    for crate::api::dart_types::MouseButton
{
    fn into_into_dart(self) -> crate::api::dart_types::MouseButton {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dart_types::MouseButtonState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Pressed => 0.into_dart(),
            Self::Released => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dart_types::MouseButtonState
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dart_types::MouseButtonState>
    for crate::api::dart_types::MouseButtonState
{
    fn into_into_dart(self) -> crate::api::dart_types::MouseButtonState {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dart_types::MouseButtonsState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.left.into_into_dart().into_dart(),
            self.middle.into_into_dart().into_dart(),
            self.right.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dart_types::MouseButtonsState
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dart_types::MouseButtonsState>
    for crate::api::dart_types::MouseButtonsState
{
    fn into_into_dart(self) -> crate::api::dart_types::MouseButtonsState {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dart_types::MouseEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.screen_pointer_position.into_into_dart().into_dart(),
            self.buttons.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dart_types::MouseEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dart_types::MouseEvent>
    for crate::api::dart_types::MouseEvent
{
    fn into_into_dart(self) -> crate::api::dart_types::MouseEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dart_types::Point2 {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.x.into_into_dart().into_dart(),
            self.y.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dart_types::Point2
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dart_types::Point2>
    for crate::api::dart_types::Point2
{
    fn into_into_dart(self) -> crate::api::dart_types::Point2 {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dart_types::UserEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::dart_types::UserEvent::ButtonPressed(field0, field1) => [
                0.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::dart_types::UserEvent::ButtonReleased(field0, field1) => [
                1.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::dart_types::UserEvent::Click(field0, field1) => [
                2.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::dart_types::UserEvent::DoubleClick(field0, field1) => [
                3.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::dart_types::UserEvent::PointerMoved(field0) => {
                [4.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::dart_types::UserEvent::DragStarted(field0, field1) => [
                5.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::dart_types::UserEvent::Drag(field0, field1, field2) => [
                6.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
                field2.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::dart_types::UserEvent::DragEnded(field0, field1) => [
                7.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::dart_types::UserEvent::Scroll(field0, field1) => [
                8.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::dart_types::UserEvent::Zoom(field0, field1) => [
                9.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dart_types::UserEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dart_types::UserEvent>
    for crate::api::dart_types::UserEvent
{
    fn into_into_dart(self) -> crate::api::dart_types::UserEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::dart_types::Vector2 {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.dx.into_into_dart().into_dart(),
            self.dy.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::dart_types::Vector2
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::dart_types::Vector2>
    for crate::api::dart_types::Vector2
{
    fn into_into_dart(self) -> crate::api::dart_types::Vector2 {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::api::CreateNewSessionResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.session_id, serializer);
        <i64>::sse_encode(self.texture_id, serializer);
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::dart_types::LayerConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::dart_types::LayerConfig::Osm => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::dart_types::LayerConfig::RasterTiles {
                url_template,
                attribution,
            } => {
                <i32>::sse_encode(1, serializer);
                <String>::sse_encode(url_template, serializer);
                <Option<String>>::sse_encode(attribution, serializer);
            }
            crate::api::dart_types::LayerConfig::VectorTiles {
                url_template,
                style_json,
                attribution,
            } => {
                <i32>::sse_encode(2, serializer);
                <String>::sse_encode(url_template, serializer);
                <String>::sse_encode(style_json, serializer);
                <Option<String>>::sse_encode(attribution, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::dart_types::MapInitConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <(f64, f64)>::sse_encode(self.latlon, serializer);
        <u32>::sse_encode(self.zoom_level, serializer);
        <crate::api::dart_types::MapSize>::sse_encode(self.map_size, serializer);
        <bool>::sse_encode(self.enable_multisampling, serializer);
        <(f32, f32, f32, f32)>::sse_encode(self.background_color, serializer);
    }
}

impl SseEncode for crate::api::dart_types::MapSize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
    }
}

impl SseEncode for crate::api::dart_types::MapViewport {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.x_min, serializer);
        <f64>::sse_encode(self.x_max, serializer);
        <f64>::sse_encode(self.y_min, serializer);
        <f64>::sse_encode(self.y_max, serializer);
    }
}

impl SseEncode for crate::api::dart_types::MouseButton {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::dart_types::MouseButton::Left => 0,
                crate::api::dart_types::MouseButton::Middle => 1,
                crate::api::dart_types::MouseButton::Right => 2,
                crate::api::dart_types::MouseButton::Other => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::dart_types::MouseButtonState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::dart_types::MouseButtonState::Pressed => 0,
                crate::api::dart_types::MouseButtonState::Released => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::dart_types::MouseButtonsState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::dart_types::MouseButtonState>::sse_encode(self.left, serializer);
        <crate::api::dart_types::MouseButtonState>::sse_encode(self.middle, serializer);
        <crate::api::dart_types::MouseButtonState>::sse_encode(self.right, serializer);
    }
}

impl SseEncode for crate::api::dart_types::MouseEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::dart_types::Point2>::sse_encode(self.screen_pointer_position, serializer);
        <crate::api::dart_types::MouseButtonsState>::sse_encode(self.buttons, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::dart_types::MapViewport> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::dart_types::MapViewport>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::dart_types::Point2 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.x, serializer);
        <f64>::sse_encode(self.y, serializer);
    }
}

impl SseEncode for (f32, f32, f32, f32) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.0, serializer);
        <f32>::sse_encode(self.1, serializer);
        <f32>::sse_encode(self.2, serializer);
        <f32>::sse_encode(self.3, serializer);
    }
}

impl SseEncode for (f64, f64) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.0, serializer);
        <f64>::sse_encode(self.1, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::dart_types::UserEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::dart_types::UserEvent::ButtonPressed(field0, field1) => {
                <i32>::sse_encode(0, serializer);
                <crate::api::dart_types::MouseButton>::sse_encode(field0, serializer);
                <crate::api::dart_types::MouseEvent>::sse_encode(field1, serializer);
            }
            crate::api::dart_types::UserEvent::ButtonReleased(field0, field1) => {
                <i32>::sse_encode(1, serializer);
                <crate::api::dart_types::MouseButton>::sse_encode(field0, serializer);
                <crate::api::dart_types::MouseEvent>::sse_encode(field1, serializer);
            }
            crate::api::dart_types::UserEvent::Click(field0, field1) => {
                <i32>::sse_encode(2, serializer);
                <crate::api::dart_types::MouseButton>::sse_encode(field0, serializer);
                <crate::api::dart_types::MouseEvent>::sse_encode(field1, serializer);
            }
            crate::api::dart_types::UserEvent::DoubleClick(field0, field1) => {
                <i32>::sse_encode(3, serializer);
                <crate::api::dart_types::MouseButton>::sse_encode(field0, serializer);
                <crate::api::dart_types::MouseEvent>::sse_encode(field1, serializer);
            }
            crate::api::dart_types::UserEvent::PointerMoved(field0) => {
                <i32>::sse_encode(4, serializer);
                <crate::api::dart_types::MouseEvent>::sse_encode(field0, serializer);
            }
            crate::api::dart_types::UserEvent::DragStarted(field0, field1) => {
                <i32>::sse_encode(5, serializer);
                <crate::api::dart_types::MouseButton>::sse_encode(field0, serializer);
                <crate::api::dart_types::MouseEvent>::sse_encode(field1, serializer);
            }
            crate::api::dart_types::UserEvent::Drag(field0, field1, field2) => {
                <i32>::sse_encode(6, serializer);
                <crate::api::dart_types::MouseButton>::sse_encode(field0, serializer);
                <crate::api::dart_types::Vector2>::sse_encode(field1, serializer);
                <crate::api::dart_types::MouseEvent>::sse_encode(field2, serializer);
            }
            crate::api::dart_types::UserEvent::DragEnded(field0, field1) => {
                <i32>::sse_encode(7, serializer);
                <crate::api::dart_types::MouseButton>::sse_encode(field0, serializer);
                <crate::api::dart_types::MouseEvent>::sse_encode(field1, serializer);
            }
            crate::api::dart_types::UserEvent::Scroll(field0, field1) => {
                <i32>::sse_encode(8, serializer);
                <f64>::sse_encode(field0, serializer);
                <crate::api::dart_types::MouseEvent>::sse_encode(field1, serializer);
            }
            crate::api::dart_types::UserEvent::Zoom(field0, field1) => {
                <i32>::sse_encode(9, serializer);
                <f64>::sse_encode(field0, serializer);
                <crate::api::dart_types::Point2>::sse_encode(field1, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::dart_types::Vector2 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.dx, serializer);
        <f64>::sse_encode(self.dy, serializer);
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
