// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/api.dart';
import 'api/dart_types.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  LayerConfig dco_decode_box_autoadd_layer_config(dynamic raw);

  @protected
  MapInitConfig dco_decode_box_autoadd_map_init_config(dynamic raw);

  @protected
  MapSize dco_decode_box_autoadd_map_size(dynamic raw);

  @protected
  MapViewport dco_decode_box_autoadd_map_viewport(dynamic raw);

  @protected
  MouseEvent dco_decode_box_autoadd_mouse_event(dynamic raw);

  @protected
  Point2 dco_decode_box_autoadd_point_2(dynamic raw);

  @protected
  UserEvent dco_decode_box_autoadd_user_event(dynamic raw);

  @protected
  Vector2 dco_decode_box_autoadd_vector_2(dynamic raw);

  @protected
  CreateNewSessionResponse dco_decode_create_new_session_response(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LayerConfig dco_decode_layer_config(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MapInitConfig dco_decode_map_init_config(dynamic raw);

  @protected
  MapSize dco_decode_map_size(dynamic raw);

  @protected
  MapViewport dco_decode_map_viewport(dynamic raw);

  @protected
  MouseButton dco_decode_mouse_button(dynamic raw);

  @protected
  MouseButtonState dco_decode_mouse_button_state(dynamic raw);

  @protected
  MouseButtonsState dco_decode_mouse_buttons_state(dynamic raw);

  @protected
  MouseEvent dco_decode_mouse_event(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  MapViewport? dco_decode_opt_box_autoadd_map_viewport(dynamic raw);

  @protected
  Point2 dco_decode_point_2(dynamic raw);

  @protected
  (double, double, double, double) dco_decode_record_f_32_f_32_f_32_f_32(
    dynamic raw,
  );

  @protected
  (double, double) dco_decode_record_f_64_f_64(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserEvent dco_decode_user_event(dynamic raw);

  @protected
  Vector2 dco_decode_vector_2(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  LayerConfig sse_decode_box_autoadd_layer_config(SseDeserializer deserializer);

  @protected
  MapInitConfig sse_decode_box_autoadd_map_init_config(
    SseDeserializer deserializer,
  );

  @protected
  MapSize sse_decode_box_autoadd_map_size(SseDeserializer deserializer);

  @protected
  MapViewport sse_decode_box_autoadd_map_viewport(SseDeserializer deserializer);

  @protected
  MouseEvent sse_decode_box_autoadd_mouse_event(SseDeserializer deserializer);

  @protected
  Point2 sse_decode_box_autoadd_point_2(SseDeserializer deserializer);

  @protected
  UserEvent sse_decode_box_autoadd_user_event(SseDeserializer deserializer);

  @protected
  Vector2 sse_decode_box_autoadd_vector_2(SseDeserializer deserializer);

  @protected
  CreateNewSessionResponse sse_decode_create_new_session_response(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LayerConfig sse_decode_layer_config(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MapInitConfig sse_decode_map_init_config(SseDeserializer deserializer);

  @protected
  MapSize sse_decode_map_size(SseDeserializer deserializer);

  @protected
  MapViewport sse_decode_map_viewport(SseDeserializer deserializer);

  @protected
  MouseButton sse_decode_mouse_button(SseDeserializer deserializer);

  @protected
  MouseButtonState sse_decode_mouse_button_state(SseDeserializer deserializer);

  @protected
  MouseButtonsState sse_decode_mouse_buttons_state(
    SseDeserializer deserializer,
  );

  @protected
  MouseEvent sse_decode_mouse_event(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  MapViewport? sse_decode_opt_box_autoadd_map_viewport(
    SseDeserializer deserializer,
  );

  @protected
  Point2 sse_decode_point_2(SseDeserializer deserializer);

  @protected
  (double, double, double, double) sse_decode_record_f_32_f_32_f_32_f_32(
    SseDeserializer deserializer,
  );

  @protected
  (double, double) sse_decode_record_f_64_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserEvent sse_decode_user_event(SseDeserializer deserializer);

  @protected
  Vector2 sse_decode_vector_2(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_layer_config(
    LayerConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_map_init_config(
    MapInitConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_map_size(MapSize self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_map_viewport(
    MapViewport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mouse_event(
    MouseEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_point_2(Point2 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_event(
    UserEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_vector_2(Vector2 self, SseSerializer serializer);

  @protected
  void sse_encode_create_new_session_response(
    CreateNewSessionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_layer_config(LayerConfig self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_map_init_config(MapInitConfig self, SseSerializer serializer);

  @protected
  void sse_encode_map_size(MapSize self, SseSerializer serializer);

  @protected
  void sse_encode_map_viewport(MapViewport self, SseSerializer serializer);

  @protected
  void sse_encode_mouse_button(MouseButton self, SseSerializer serializer);

  @protected
  void sse_encode_mouse_button_state(
    MouseButtonState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mouse_buttons_state(
    MouseButtonsState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mouse_event(MouseEvent self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_map_viewport(
    MapViewport? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_point_2(Point2 self, SseSerializer serializer);

  @protected
  void sse_encode_record_f_32_f_32_f_32_f_32(
    (double, double, double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_f_64_f_64(
    (double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_event(UserEvent self, SseSerializer serializer);

  @protected
  void sse_encode_vector_2(Vector2 self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
